# -*- coding: utf-8 -*-
"""Text_to_image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rApJS2SwznrZ5O6kwKhCckVAeKsbbU__
"""

pip install diffusers transformers accelerate safetensors

from diffusers import StableDiffusionPipeline
import torch

# Load the pre-trained model (you can change the model name if needed)
model_id = "runwayml/stable-diffusion-v1-5"

# Load pipeline (using CPU or GPU if available)
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda" if torch.cuda.is_available() else "cpu")

# Define your prompt
prompt = "Boat in river"

# Generate image
image = pipe(prompt).images[0]

# display the image
display(image)